# Generated by Django 5.2.8 on 2025-12-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_tracker', '0001_initial'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyusage',
            unique_together={('household', 'date')},
        ),
    ]
